pipeline {
    agent none
    environment {
        DOCKER_ID = "philjim"
        DOCKER_PASSWORD = credentials('dockerlogin')
    }
    stages{
        stage('test'){
        agent{
                docker{
                    image 'python:2.7.16-slim'
                    args '--user root'
                }
            }
            when{
                changeset "**/vote/**"
            }
            steps{
                echo "Compile and test the vote app"
                dir ('vote'){
                    sh 'pip install -r requirements.txt'
                    sh 'nosetests -v'
                }
            }
        }
        stage('docker-package'){
            agent any
            when{
                branch 'master'
                changeset "**/vote/**"
            }
            steps{
                echo "package the result vote with docker"
                script{
                    docker.withRegistry('https://index.docker.io/v1'){
                        sh 'echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin'
                        def resultImage = docker.build("philjim/vote:${env.BUILD_ID}","./vote")
                        voteImage.push()
                        voteImage.push("latest")
                    }
                }
            }
        }
    }

    post{
        always{
            echo "build pipeline completed"
        }
    }
}