pipeline {
    agent any
    tools{
        maven 'maven3.8.6'
    }
    stages{
        stage('build'){
            steps{
                echo "Compile the worker app"
                dir ('worker'){
                    sh 'mvn compile'
                }
            }
        }
        stage('test'){
            steps{
                echo "Run Unit Tests on Worker app"
                dir ('worker'){
                    sh 'mvn clean test'
                }
            }
        }
        stage('package'){
            steps{
                echo "package the worker app"
                dir ('worker'){
                    sh 'mvn package'
                }
            }
        }
    }

    post{
        always{
            echo "build pipeline completed"
        }
    }
}