pipeline {
    agent any
    tools{
        maven 'maven3.8.6'
    }
    stages{
        stage('build'){
            when{
                changeset "**/worker/**"
            }
            steps{
                echo "Compile the worker app"
                dir ('worker'){
                    sh 'mvn compile'
                }
            }
        }
        stage('test'){
            when{
                changeset "**/worker/**"
            }
            steps{
                echo "Run Unit Tests on Worker app"
                dir ('worker'){
                    sh 'mvn clean test'
                }
            }
        }
        stage('package'){
            when{
                branch 'master'
                changeset "**/worker/**"
            }
            steps{
                echo "package the worker app"
                dir ('worker'){
                    sh 'mvn package -DskipTests'
                    archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
                }
            }
        }
    }

    post{
        always{
            echo "build pipeline completed"
        }
    }
}